# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           "blog/:title.html"
#relative_permalinks: true

# Setup
title:               Kevin Ha
tagline:             Ph.D. candidate in computational biology 
paginate:            3
paginate_path:       "blog/page:num/"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kevin Ha
  email:             k.ha@mail.utoronto.ca

# Custom variables
github_username:     kcha
linkedin_username:   kevinchha

gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:
  Projects: '/projects/'
  Blog: '/blog/'
  Archive: '/archive/'


